CREATE DATABASE IF NOT EXISTS TrackerExpenses_db;
USE TrackerExpenses_db;
CREATE TABLE IF NOT EXISTS Users (
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Username VARCHAR(256) NOT NULL,
    Password VARCHAR(256) NOT NULL,
    Email VARCHAR(256) NOT NULL
);
CREATE TABLE IF NOT EXISTS Categories (
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Name VARCHAR(256) NOT NULL
);
CREATE TABLE  IF NOT EXISTS Expenses (
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Amount FLOAT NOT NULL CHECK (Amount>=0),
    Expense_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Description VARCHAR(256),
    Category_ID INT NOT NULL,
    User_ID INT NOT NULL,
    FOREIGN KEY (Category_ID) REFERENCES Categories(ID),
    FOREIGN KEY (USER_ID) REFERENCES Users(ID)
);
CREATE TABLE IF NOT EXISTS Budgets(
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Amount FLOAT NOT NULL CHECK (Amount>=0),
    User_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES Users(ID)
);